/**
 * Patient Search & Autocomplete Module
 * Provides intelligent patient search with history and suggestions
 */

function normalizeQueryText(value) {
    if (value === null || value === undefined) {
        return '';
    }
    return String(value).trim().toLowerCase();
}

function getPatientNameLabel(patient) {
    if (!patient) return '';
    const direct = patient.display_name || patient.displayName;
    if (direct && direct !== 'N/A') {
        return direct;
    }
    const first = patient.First_Name || patient.first_name || patient.first;
    const last = patient.Last_Name || patient.last_name || patient.last;
    if (first || last) {
        if (first && last) {
            return `${first} ${last}`;
        }
        return first || last;
    }
    return '';
}

function getPatientNameTokens(patient) {
    if (!patient) return [];
    const tokens = [];
    const nameLabel = normalizeQueryText(getPatientNameLabel(patient));
    if (nameLabel) {
        tokens.push(nameLabel);
    }

    const first = normalizeQueryText(patient.First_Name || patient.first_name || patient.first);
    const last = normalizeQueryText(patient.Last_Name || patient.last_name || patient.last);
    if (first && last) {
        tokens.push(`${first} ${last}`);
        tokens.push(`${last} ${first}`);
        tokens.push(`${last}, ${first}`);
    }
    if (first) tokens.push(first);
    if (last) tokens.push(last);
    return tokens.filter(Boolean);
}

function formatPatientIdLabel(patient) {
    if (!patient) return '';
    const rawId = (patient.patient_id ?? '').toString().trim();
    const fallback = rawId || 'AUTO ID';
    return patient.auto_generated_id ? `${fallback} (Auto ID)` : fallback;
}

class PatientSearch {
    constructor() {
        this.searchHistory = [];
        this.maxHistoryItems = 10;
        this.allPatients = [];
        this.loadSearchHistory();
    }

    /**
     * Load search history from localStorage
     */
    loadSearchHistory() {
        try {
            const saved = localStorage.getItem('patient_search_history');
            if (saved) {
                this.searchHistory = JSON.parse(saved);
            }
        } catch (error) {
            console.error('Error loading search history:', error);
            this.searchHistory = [];
        }
    }

    /**
     * Save search history to localStorage
     */
    saveSearchHistory() {
        try {
            localStorage.setItem('patient_search_history', JSON.stringify(this.searchHistory));
        } catch (error) {
            console.error('Error saving search history:', error);
        }
    }

    /**
     * Add patient to search history
     */
    addToHistory(patientId, patientData) {
        // Remove if already exists
        this.searchHistory = this.searchHistory.filter(item => item.id !== patientId);
        
        // Add to beginning
        this.searchHistory.unshift({
            id: patientId,
            timestamp: Date.now(),
            cluster: patientData.cluster,
            age: patientData.age,
            gender: patientData.gender,
            autoGenerated: !!patientData.auto_generated_id,
            name: getPatientNameLabel(patientData)
        });
        
        // Keep only last N items
        if (this.searchHistory.length > this.maxHistoryItems) {
            this.searchHistory = this.searchHistory.slice(0, this.maxHistoryItems);
        }
        
        this.saveSearchHistory();
    }

    /**
     * Clear search history
     */
    clearHistory() {
        this.searchHistory = [];
        this.saveSearchHistory();
    }

    /**
     * Get search suggestions based on query
     */
    getSuggestions(query, limit = 5) {
        if (!query) return [];
        
        const queryLower = query.toLowerCase();
        const suggestions = [];
        
        // Search by ID only (names hidden for privacy but still searchable)
        this.allPatients.forEach(patient => {
            const patientIdRaw = (patient.patient_id ?? '').toString();
            const patientId = patientIdRaw.toLowerCase();
            const nameTokens = getPatientNameTokens(patient);
            const matchesId = patientId.includes(queryLower);
            const matchesName = nameTokens.some(token => token.includes(queryLower));
            if (matchesId || matchesName) {
                const idLabel = formatPatientIdLabel(patient);
                // Hide name for privacy - only show ID
                const displayLabel = `Patient ${idLabel}`;
                suggestions.push({
                    type: 'id',
                    patient_id: patient.patient_id,
                    cluster: patient.cluster,
                    confidence: patient.confidence,
                    label: `${displayLabel} (Cluster ${patient.cluster})`
                });
            }
        });
        
        return suggestions.slice(0, limit);
    }

    /**
     * Setup autocomplete on input field
     */
    setupAutocomplete(inputId, resultsContainerId) {
        const input = document.getElementById(inputId);
        const resultsContainer = document.getElementById(resultsContainerId);
        
        if (!input || !resultsContainer) return;
        
        let debounceTimer;
        
        // Handle input
        input.addEventListener('input', (e) => {
            clearTimeout(debounceTimer);
            
            debounceTimer = setTimeout(() => {
                const query = e.target.value.trim();
                
                if (query.length < 1) {
                    this.hideSuggestions(resultsContainer);
                    return;
                }
                
                const suggestions = this.getSuggestions(query);
                this.displaySuggestions(suggestions, resultsContainer, input);
            }, 300);
        });
        
        // Handle blur - hide suggestions after a delay
        input.addEventListener('blur', () => {
            setTimeout(() => {
                this.hideSuggestions(resultsContainer);
            }, 200);
        });
        
        // Handle focus - show history if empty
        input.addEventListener('focus', () => {
            if (input.value.trim() === '' && this.searchHistory.length > 0) {
                this.displaySearchHistory(resultsContainer, input);
            }
        });
    }

    /**
     * Display autocomplete suggestions
     */
    displaySuggestions(suggestions, container, input) {
        if (suggestions.length === 0) {
            this.hideSuggestions(container);
            return;
        }
        
        container.innerHTML = '';
        container.style.display = 'block';
        
        suggestions.forEach(suggestion => {
            const item = document.createElement('div');
            item.className = 'autocomplete-item';
            item.innerHTML = `
                <div class="autocomplete-item-main">
                    <span class="autocomplete-item-label">${suggestion.label}</span>
                </div>
                <div class="autocomplete-item-meta">
                    ${suggestion.confidence ? `<span class="autocomplete-confidence">${(suggestion.confidence * 100).toFixed(0)}%</span>` : ''}
                </div>
            `;
            
            item.addEventListener('click', () => {
                input.value = suggestion.patient_id;
                this.hideSuggestions(container);
                
                // Trigger search
                const event = new Event('autocomplete-select');
                event.patientId = suggestion.patient_id;
                input.dispatchEvent(event);
            });
            
            container.appendChild(item);
        });
    }

    /**
     * Display search history
     */
    displaySearchHistory(container, input) {
        if (this.searchHistory.length === 0) return;
        
        container.innerHTML = '';
        container.style.display = 'block';
        
        // Header
        const header = document.createElement('div');
        header.className = 'autocomplete-header';
        header.innerHTML = `
            <span>Recent Searches</span>
            <button class="clear-history-btn" id="clearHistoryBtn">Clear</button>
        `;
        container.appendChild(header);
        
        // History items
        this.searchHistory.forEach(item => {
            const div = document.createElement('div');
            div.className = 'autocomplete-item history-item';
            div.innerHTML = `
                <div class="autocomplete-item-main">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="margin-right: 8px;">
                        <circle cx="12" cy="12" r="10"></circle>
                        <polyline points="12 6 12 12 16 14"></polyline>
                    </svg>
                    <span>Patient ${item.autoGenerated ? `${item.id} (Auto ID)` : item.id}</span>
                </div>
                <div class="autocomplete-item-meta">
                    <span class="cluster-badge-small">C${item.cluster}</span>
                </div>
            `;
            
            div.addEventListener('click', () => {
                input.value = item.id;
                this.hideSuggestions(container);
                
                // Trigger search
                const event = new Event('autocomplete-select');
                event.patientId = item.id;
                input.dispatchEvent(event);
            });
            
            container.appendChild(div);
        });
        
        // Clear history button
        const clearBtn = document.getElementById('clearHistoryBtn');
        if (clearBtn) {
            clearBtn.addEventListener('click', (e) => {
                e.stopPropagation();
                this.clearHistory();
                this.hideSuggestions(container);
            });
        }
    }

    /**
     * Hide suggestions
     */
    hideSuggestions(container) {
        container.style.display = 'none';
        container.innerHTML = '';
    }

    /**
     * Load all patients data for searching
     */
    setPatientData(patients) {
        this.allPatients = patients;
    }

    /**
     * Get recent searches
     */
    getRecentSearches(limit = 5) {
        return this.searchHistory.slice(0, limit);
    }
}

// Create global instance
const patientSearch = new PatientSearch();

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { PatientSearch, patientSearch };
}
